name = "cfly"
main = "src/index.js"
compatibility_date = "2025-01-01"
minify = true

# 部署后请用以下命令设置变量（不会随代码更新丢失）：
#   wrangler secret put DOMAIN
#   wrangler secret put INTRANET_URL

[[kv_namespaces]]
binding = "LINKS"
id = "0805b8f7a75d4ed8872eb5f97248bed5"
